version: "3.8"
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    env_file:
      - .env.development.local
    ports:
      - 27017:27017
  testapi:
    container_name: testapi
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.development.local
    ports:
      - 3030:3030
    external_links:
      - mongo
    depends_on:
      - mongo
volumes:
  mongo-data:
    driver: local